apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- admin-group.yaml
- cluster-role-binding.yaml
- developer-group.yaml
- marketing-group.yaml
- project-role-binding-pricelist.yaml
