apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- htpass-auth.yaml
- rbac.yaml
- pipelines.yaml
- container-security-operator.yaml
- pricelist-app.yaml
- sealed-secrets.yaml
