apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- htpass-auth.yaml
- rbac.yaml
- container-security-operator.yaml
- pricelist-frontend.yaml
- pricelist-db.yaml
- pricelist-namespace.yaml
