- op: remove
  path: /spec/template/spec/containers/0/securityContext
- op: remove
  path: /spec/template/spec/securityContext
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: SEALED_SECRETS_UPDATE_STATUS
      value: '1'
